"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [scrolled, setScrolled] = useState(false);

  const toggleButton = () => {
    if (window.scrollY >= 300) setScrolled(true);
    else setScrolled(false);
  };
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };
  window.addEventListener("scroll", toggleButton);

  return (
    <html lang="en">
      <body className="relative">
        {children}
        <div
          onClick={() => {
            scrollToTop;
          }}
          style={{
            right: scrolled ? "32px" : "-32px",
            opacity: scrolled ? "1" : "0",
          }}
          className="rounded-full w-8 h-8 fixed bottom-8 transition-all ease-linear bg-neutral-800 text-white text-center"
        >
          <div
            onClick={scrollToTop}
            className="cursor-pointer absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-2 h-2 border-2 rotate-45 border-b-transparent border-r-transparent border-white"
          ></div>
        </div>
      </body>
    </html>
  );
}
